services:
  - type: web
    name: music-backend
    env: python
    buildCommand: |
      # התקנת חבילות מערכת קריטיות לאודיו ב-Render לפני התקנת הפייתון
      apt-get update && apt-get install -y fluidsynth fluid-soundfont-gm ffmpeg
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
